io:
  output_fps: 25
  output_size: [640, 360]
  prefetch: 16
  write_queue: 64
  cpu_threads: 0
  warmup_iters: 12
  mem_gc_every: 0

camera:
  height_m: 1.35
  fov_deg_h: 68.0
  principal: [0.5, 0.5]

models:
  yolo:
    weights: "models/yolov12/yolov12m.pt"
    conf: 0.40
    iou: 0.60
    half: true
    imgsz: [896, 512]
    whitelist_classes:
      - 0    # person
      - 1    # bicycle
      - 2    # car
      - 3    # motorcycle
      # - 4    # airplane
      - 5    # bus
      # - 6    # train
      - 7    # truck
      - 8    # boat
      - 9    # traffic light
      - 10   # fire hydrant
      - 11   # stop sign
      # - 12  # parking meter
      - 13   # bench
      # - 14  # bird
      # - 15  # cat
      # - 16  # dog
      # - 17  # horse
      # - 18  # sheep
      # - 19  # cow
      # - 20  # elephant
      # - 21  # bear
      # - 22  # zebra
      # - 23  # giraffe
      - 24   # backpack
      - 25   # umbrella
      - 26   # handbag
      - 27   # tie
      - 28   # suitcase
      - 29   # frisbee
      - 30   # skis
      - 31   # snowboard
      - 32   # sports ball
      - 33   # kite
      - 34   # baseball bat
      - 35   # baseball glove
      - 36   # skateboard
      - 37   # surfboard
      - 38   # tennis racket
      - 39   # bottle
      - 40   # wine glass
      - 41   # cup
      - 42   # fork
      - 43   # knife
      - 44   # spoon
      - 45   # bowl
      - 46   # banana
      - 47   # apple
      - 48   # sandwich
      - 49   # orange
      - 50   # broccoli
      - 51   # carrot
      - 52   # hot dog
      - 53   # pizza
      - 54   # donut
      - 55   # cake
      - 56   # chair
      - 57   # couch
      - 58   # potted plant
      - 59   # bed
      - 60   # dining table
      - 61   # toilet
      - 62   # tv
      - 63   # laptop
      # - 64  # mouse
      # - 65  # remote
      - 66   # keyboard
      - 67   # cell phone
      - 68   # microwave
      - 69   # oven
      - 70   # toaster
      - 71   # sink
      - 72   # refrigerator
      - 73   # book
      - 74   # clock
      - 75   # vase
      - 76   # scissors
      - 77   # teddy bear
      - 78   # hair drier
      - 79   # toothbrush

  segmentation:
    weights: "models/bisenet_v2/weights/bisenetv2_cityscapes.pth"
    half: true
    run_every_k: 3

  depth:
    encoder: "vits"
    checkpoint: "models/video_depth_anything/checkpoints/video_depth_anything_vits.pth"
    input_size: 518
    stream: true
    fp32: false
    xformers: true

tracking:
  yolo:
    max_age: 1
    iou: 0.3
  obs:
    max_age: 0
    iou: 0.5
    # --- staging/commit ---
    staging:
      window: 6
      min_hits: 4
      iou_min: 0.35
      twoedge_min: 3
      z_mad_max: 0.6
      yolo_cover_thr: 0.90
      yolo_iou_thr: 0.60
    # --- lock/hysteresis sau commit ---
    lock:
      search_dx_px: 8
      search_dy_px: 8
      ema_beta: 0.80
      max_scale_change: 0.15

fusion:
  distance_thresholds_m: [1.8, 3.5]

  plane_fit:
    method: ransac
    inlier_thr_m: 0.05
    max_iter: 180
    sample_stride: 4
    ema_beta: 0.9
    use_sidewalk: true
    use_terrain: true

  edge_enhance:
    gauss_k: 5
    gauss_sigma: 1.2
    log_eps: 1e-6

  epp:
    edge_percentile_str: 92.0
    edge_percentile_weak: 85.0
    mag_thr_rel: 1.0
    mag_thr_rel_weak: 0.85
    gauss_k: 5
    gauss_sigma: 1.15
    depth_min_m: 0.35
    depth_max_m: 15.0
    area_min_m2_k: 3.0e-4
    snap_dx_px: 24
    snap_dy_px: 24
    min_w_px: 8
    min_h_px: 8
    snap_ignore_bottom_frac: 0.12
    bottom_h_free_m: 0.05
    bottom_band_px: 12
    bottom_min_drop_m: 0.10
    twoedge_band_px: 3
    twoedge_v_min: 0.0025
    twoedge_h_min: 0.0025
    tile_rows: 3
    tile_cols: 6

  ppp:
    depth_min_m: 0.35
    depth_max_m: 15.0
    sigma_thr: 0.05
    grad_thr_in: 0.02
    area_min_m2_k: 4.0e-4
    min_w_px: 12
    min_h_px: 12
    h_min_m: 0.05

  edge_inside:
    ribbon_px: 3
    search_dx_px: 18
    search_dy_px: 14
    jump_min_m: 0.25
    var_in_max: 0.08
    fill_min: 0.55

  pole:
    min_len_px: 28
    max_w_px: 16
    nms_x_px: 12

  obs_sliver:
    min_w_px: 10
    min_h_px: 10
    min_area_px: 64
    slender_ar_min: 2.8
    slender_w_max_px: 20
    center_merge_px: 22
    center_z_thr_m: 0.6
    yolo_cover_thr: 0.90
    z_min_keep_m: 0.2
    z_max_keep_m: 80.0

  z_max_obs_m: 15.0

  depth_calib:
    gamma: 0.95    # 0.8–0.9 để nén mạnh phần xa
    scale: 0.4     # tính theo công thức ở trên để “neo” đúng mốc gần

viz:
  thickness: 2
  font_scale: 0.45
  show_fps: true  