io:
  output_fps: 25
  output_size: [640, 360]
  prefetch: 8
  write_queue: 64
  cpu_threads: 0
  warmup_iters: 12

camera:
  height_m: 1.35
  fov_deg_h: 68.0
  principal: [0.5, 0.5]

models:
  yolo:
    weights: "models/yolov12/yolov12m.pt"
    conf: 0.40
    iou: 0.60
    half: true
    imgsz: [896, 512]
    whitelist_classes:
      - 0    # person
      - 1    # bicycle
      - 2    # car
      - 3    # motorcycle
      # - 4    # airplane
      - 5    # bus
      # - 6    # train
      - 7    # truck
      - 8    # boat
      - 9    # traffic light
      - 10   # fire hydrant
      - 11   # stop sign
      # - 12  # parking meter
      - 13   # bench
      # - 14  # bird
      # - 15  # cat
      # - 16  # dog
      # - 17  # horse
      # - 18  # sheep
      # - 19  # cow
      # - 20  # elephant
      # - 21  # bear
      # - 22  # zebra
      # - 23  # giraffe
      - 24   # backpack
      - 25   # umbrella
      - 26   # handbag
      - 27   # tie
      - 28   # suitcase
      - 29   # frisbee
      - 30   # skis
      - 31   # snowboard
      - 32   # sports ball
      - 33   # kite
      - 34   # baseball bat
      - 35   # baseball glove
      - 36   # skateboard
      - 37   # surfboard
      - 38   # tennis racket
      - 39   # bottle
      - 40   # wine glass
      - 41   # cup
      - 42   # fork
      - 43   # knife
      - 44   # spoon
      - 45   # bowl
      - 46   # banana
      - 47   # apple
      - 48   # sandwich
      - 49   # orange
      - 50   # broccoli
      - 51   # carrot
      - 52   # hot dog
      - 53   # pizza
      - 54   # donut
      - 55   # cake
      - 56   # chair
      - 57   # couch
      - 58   # potted plant
      - 59   # bed
      - 60   # dining table
      - 61   # toilet
      - 62   # tv
      - 63   # laptop
      # - 64  # mouse
      # - 65  # remote
      - 66   # keyboard
      - 67   # cell phone
      - 68   # microwave
      - 69   # oven
      - 70   # toaster
      - 71   # sink
      - 72   # refrigerator
      - 73   # book
      - 74   # clock
      - 75   # vase
      - 76   # scissors
      - 77   # teddy bear
      - 78   # hair drier
      - 79   # toothbrush

  segmentation:
    weights: "models/bisenet_v2/weights/bisenetv2_cityscapes.pth"
    half: true
    run_every_k: 3

  depth:
    encoder: "vits"
    checkpoint: "models/video_depth_anything/checkpoints/video_depth_anything_vits.pth"
    input_size: 518
    stream: true
    fp32: false
    xformers: true

tracking:
  yolo:
    max_age: 1
    iou: 0.3
  obs:
    max_age: 1
    iou: 0.3

fusion:
  edge_obstacle:
    edge_percentile_str: 96.0
    edge_percentile_weak: 92.0
    mag_thr_rel: 1.20
    mag_thr_rel_weak: 1.00
    gauss_k: 5
    gauss_sigma: 1.15
    depth_min_m: 0.35
    depth_max_m: 12.0
    area_min_m2_k: 6.0e-4
    snap_dx_px: 24
    snap_dy_px: 24
    min_w_px: 10
    min_h_px: 10
    snap_ignore_bottom_frac: 0.10
    bottom_h_free_m: 0.07
    bottom_band_px: 12
    bottom_min_drop_m: 0.12

  bev:
    win: 2
    boost_lambda: 0.15   # giảm nhẹ boost để tránh khuếch đại nhiễu

  obstacle:
    nms_iou: 0.45
    topk: 15

  depth_percentile:
    yolo_q: 0.40
    obs_q: 0.35
    foot_band_px: 12

  depth_metric:
    scale_k: 2.2        # tăng lên -> khoảng cách lớn hơn, giảm xuống -> nhỏ hơn
    median_region: bottom
    region_frac: 0.5    # dùng nửa dưới khung hình
    clip_min_m: 0.2
    clip_max_m: 80.0

  obs_sliver:
    min_w_px: 8
    min_h_px: 8
    min_area_px: 64
    slender_ar_min: 2.8
    slender_w_max_px: 20
    center_merge_px: 22
    center_z_thr_m: 0.6
    yolo_cover_thr: 0.90
    z_min_keep_m: 0.2
    z_max_keep_m: 80.0
    
viz:
  thickness: 2
  font_scale: 0.45
  show_fps: true
