train: ../data/images/train
val:   ../data/images/val

nc: 18

names:
  0: person
  1: car
  2: motorbike
  3: bicycle
  4: pole
  5: tree
  6: stair
  7: step_up
  8: step_down
  9: pothole
  10: uneven_surface
  11: ramp
  12: road_median
  13: curb
  14: obstacle
  15: truck
  16: wall
  17: handrail